insert into author_letters (letter) values ('А');
insert into author_letters (letter) values ('Б');
insert into author_letters (letter) values ('В');
insert into author_letters (letter) values ('Г');
insert into author_letters (letter) values ('Д');
insert into author_letters (letter) values ('Е');
insert into author_letters (letter) values ('Ё');
insert into author_letters (letter) values ('Ж');
insert into author_letters (letter) values ('З');
insert into author_letters (letter) values ('И');
insert into author_letters (letter) values ('Й');
insert into author_letters (letter) values ('К');
insert into author_letters (letter) values ('Л');
insert into author_letters (letter) values ('М');
insert into author_letters (letter) values ('Н');
insert into author_letters (letter) values ('О');
insert into author_letters (letter) values ('П');
insert into author_letters (letter) values ('Р');
insert into author_letters (letter) values ('С');
insert into author_letters (letter) values ('Т');
insert into author_letters (letter) values ('У');
insert into author_letters (letter) values ('Ф');
insert into author_letters (letter) values ('Х');
insert into author_letters (letter) values ('Ц');
insert into author_letters (letter) values ('Ч');
insert into author_letters (letter) values ('Ш');
insert into author_letters (letter) values ('Щ');
insert into author_letters (letter) values ('Э');
insert into author_letters (letter) values ('Ю');
insert into author_letters (letter) values ('Я');

insert into author_letters (letter) values ('A');
insert into author_letters (letter) values ('B');
insert into author_letters (letter) values ('C');
insert into author_letters (letter) values ('D');
insert into author_letters (letter) values ('E');
insert into author_letters (letter) values ('F');
insert into author_letters (letter) values ('J');
insert into author_letters (letter) values ('H');
insert into author_letters (letter) values ('I');
insert into author_letters (letter) values ('J');
insert into author_letters (letter) values ('K');
insert into author_letters (letter) values ('L');
insert into author_letters (letter) values ('M');
insert into author_letters (letter) values ('N');
insert into author_letters (letter) values ('O');
insert into author_letters (letter) values ('P');
insert into author_letters (letter) values ('Q');
insert into author_letters (letter) values ('R');
insert into author_letters (letter) values ('S');
insert into author_letters (letter) values ('T');
insert into author_letters (letter) values ('U');
insert into author_letters (letter) values ('V');
insert into author_letters (letter) values ('W');
insert into author_letters (letter) values ('X');
insert into author_letters (letter) values ('Y');
insert into author_letters (letter) values ('Z');

insert into authors (author_letters_id,first_name,last_name) values ('38','Drucie','Goodbourn');
insert into authors (author_letters_id,first_name,last_name) values ('32','Marcia','Aggiss');
insert into authors (author_letters_id,first_name,last_name) values ('33','Giovanni','Bigg');
insert into authors (author_letters_id,first_name,last_name) values ('36','Duffie','Eynon');
insert into authors (author_letters_id,first_name,last_name) values ('44','Anselma','McKennan');
insert into authors (author_letters_id,first_name,last_name) values ('42','Gert','Kira');
insert into authors (author_letters_id,first_name,last_name) values ('35','Clerc','Djakovic');
insert into authors (author_letters_id,first_name,last_name) values ('36','Stacee','Elsy');
insert into authors (author_letters_id,first_name,last_name) values ('33','Dorotea','Bonhill');
insert into authors (author_letters_id,first_name,last_name) values ('33','Minni','Bunney');
insert into authors (author_letters_id,first_name,last_name) values ('38','Berty','Gandley');
insert into authors (author_letters_id,first_name,last_name) values ('51','Raynard','Tesdale');
insert into authors (author_letters_id,first_name,last_name) values ('39','Joanna','Hutfield');
insert into authors (author_letters_id,first_name,last_name) values ('38','Dannie','Glidder');
insert into authors (author_letters_id,first_name,last_name) values ('32','Timmie','Adshede');
insert into authors (author_letters_id,first_name,last_name) values ('45','Fernando','Neads');
insert into authors (author_letters_id,first_name,last_name) values ('38','Teddy','Guilliland');
insert into authors (author_letters_id,first_name,last_name) values ('38','Paloma','Grebert');
insert into authors (author_letters_id,first_name,last_name) values ('52','Kristos','Usher');
insert into authors (author_letters_id,first_name,last_name) values ('49','Darcey','Rohmer');
insert into authors (author_letters_id,first_name,last_name) values ('40','Cristie','Isacsson');
insert into authors (author_letters_id,first_name,last_name) values ('34','Lindsay','Coutthart');
insert into authors (author_letters_id,first_name,last_name) values ('50','Helyn','Schneidar');
insert into authors (author_letters_id,first_name,last_name) values ('32','Bette-Ann','Askem');
insert into authors (author_letters_id,first_name,last_name) values ('49','Dom','Robuchon');

insert into books (authors_id, author, title, priceOld, price) values ('1','Drucie Goodbourn', 'Exploit real-time e-commerce', '$203.23', '$43.37');
insert into books (authors_id, author, title, priceOld, price) values ('2','Marcia Aggiss', 'Utilize real-time interfaces', '$260.31', '$35.96');
insert into books (authors_id, author, title, priceOld, price) values ('3','Giovanni Bigg', 'Extend strategic e-services', '$272.00', '$151.04');
insert into books (authors_id, author, title, priceOld, price) values ('4','Duffie Eynon', 'Iterate integrated solutions', '$271.58', '$141.40');
insert into books (authors_id, author, title, priceOld, price) values ('5','Anselma McKennan', 'Cultivate magnetic e-commerce', '$278.43', '$54.44');
insert into books (authors_id, author, title, priceOld, price) values ('6','Gert Kira', 'Architect vertical ROI', '$282.54', '$102.61');
insert into books (authors_id, author, title, priceOld, price) values ('7','Clerc Djakovic', 'Disintermediate extensible architectures', '$295.38', '$181.27');
insert into books (authors_id, author, title, priceOld, price) values ('8','Stacee Elsy', 'Extend leading-edge methodologies', '$283.08', '$97.96');
insert into books (authors_id, author, title, priceOld, price) values ('9','Dorotea Bonhill', 'Integrate one-to-one systems', '$258.51', '$52.25');
insert into books (authors_id, author, title, priceOld, price) values ('10','Minni Bunney', 'Revolutionize 24/7 infrastructures', '$260.79', '$33.69');
insert into books (authors_id, author, title, priceOld, price) values ('11','Berty Gandley', 'Enhance innovative e-services', '$256.54', '$160.98');
insert into books (authors_id, author, title, priceOld, price) values ('12','Raynard Tesdale', 'Maximize 24/365 e-tailers', '$262.07', '$34.06');
insert into books (authors_id, author, title, priceOld, price) values ('13','Joanna Hutfield', 'Scale integrated architectures', '$257.66', '$32.97');
insert into books (authors_id, author, title, priceOld, price) values ('14','Dannie Glidder', 'E-enable frictionless web services', '$288.19', '$90.52');
insert into books (authors_id, author, title, priceOld, price) values ('15','Timmie Adshede', 'Strategize B2B channels', '$232.27', '$44.83');
insert into books (authors_id, author, title, priceOld, price) values ('16','Fernando Neads', 'Syndicate compelling deliverables', '$287.45', '$101.89');
insert into books (authors_id, author, title, priceOld, price) values ('17','Teddy Guilliland', 'Utilize bleeding-edge users', '$281.37', '$146.21');
insert into books (authors_id, author, title, priceOld, price) values ('18','Paloma Grebert', 'Cultivate 24/365 networks', '$270.99', '$184.76');
insert into books (authors_id, author, title, priceOld, price) values ('19','Kristos Usher', 'Embrace plug-and-play platforms', '$278.36', '$77.71');
insert into books (authors_id, author, title, priceOld, price) values ('20','Darcey Rohmer', 'Target innovative paradigms', '$298.94', '$130.01');
insert into books (authors_id, author, title, priceOld, price) values ('21','Cristie Isacsson', 'Generate open-source e-business', '$276.57', '$113.25');
insert into books (authors_id, author, title, priceOld, price) values ('22','Lindsay Coutthart', 'Implement user-centric e-markets', '$254.70', '$115.31');
insert into books (authors_id, author, title, priceOld, price) values ('23','Helyn Schneidar', 'Utilize magnetic supply-chains', '$279.70', '$77.86');
insert into books (authors_id, author, title, priceOld, price) values ('24','Bette-Ann Askem', 'E-enable dot-com supply-chains', '$297.83', '$110.15');
insert into books (authors_id, author, title, priceOld, price) values ('25','Dom Robuchon', 'Facilitate efficient eyeballs', '$232.30', '$131.48');
